states = {
'Alabama' :         {'Capital': 'Montgomery',       'Flower': 'Camellia',                   'Population': '4903185'},
'Alaska' :          {'Capital': 'Juneau',           'Flower': 'Forget Me Not',              'Population': '731545'},
'Arizona' :         {'Capital': 'Phoenix',          'Flower': 'Saguaro cactus blossom',     'Population': '7278717'},
'Arkansas' :        {'Capital': 'Little Rock',      'Flower': 'Apple blossom',              'Population': '3017804'},
'California' :      {'Capital': 'Sacramento',       'Flower': 'Golden poppy',               'Population': '39512223'},
'Colorado' :        {'Capital': 'Denver',           'Flower': 'Rocky Mountain columbine',   'Population': '5758736'},
'Connecticut' :     {'Capital': 'Hartford<br>',     'Flower': 'Mountain laurel',            'Population': '3565287'},
'Delaware' :        {'Capital': 'Dover',            'Flower': 'Peach blossom',              'Population': '973764'},
'Florida' :         {'Capital': 'Honolulu',         'Flower': 'Orange blossom',             'Population': '21477737'},
'Georgia' :         {'Capital': 'Tallahassee',      'Flower': 'Cherokee rose',              'Population': '10617423'},
'Hawaii' :          {'Capital': 'Atlanta',          'Flower': 'Hibiscus',                   'Population': '1415872'},
'Idaho' :           {'Capital': 'Boise',            'Flower': 'Syringa',                    'Population': '1787065'},
'Illinois' :        {'Capital': 'Springfield',      'Flower': 'Violet',                     'Population': '12671821'},
'Indiana' :         {'Capital': 'Indianapolis',     'Flower': 'Peony',                      'Population': '6732219'},
'Iowa' :            {'Capital': 'Des Moines',       'Flower': 'Wild rose',                  'Population': '3155070'},
'Kansas' :          {'Capital': 'Topeka',           'Flower': 'Sunflower',                  'Population': '2913314',},
'Kentucky' :        {'Capital': 'Frankfort',        'Flower': 'Goldenrod',                  'Population': '4467673'},
'Louisiana' :       {'Capital': 'Baton Rouge',      'Flower': 'Magnolia',                   'Population': '4648794'},
'Maine' :           {'Capital': 'Augusta',          'Flower': 'White pine cone and tassel', 'Population': '1344212'},
'Maryland' :        {'Capital': 'Annapolis',        'Flower': 'Black-eyed susan',           'Population': '6045680'},
'Massachusetts' :   {'Capital': 'Boston',           'Flower': 'Mayflower',                  'Population': '6892503'},
'Michigan' :        {'Capital': 'Lansing',          'Flower': 'Apple blossom',              'Population': '9986857'},
'Minnesota' :       {'Capital': 'St. Paul',         'Flower': 'Lady slipper',               'Population': '5639632'},
'Mississippi' :     {'Capital': 'Jackson',          'Flower': 'magnolia',                   'Population': '2976149'},
'Missouri' :        {'Capital': 'Jefferson City',   'Flower': 'Hawthorn',                   'Population': '6137428'},
'Montana' :         {'Capital': 'Helena',           'Flower': 'Bitterroot',                 'Population': '1068778'},
'Nebraska' :        {'Capital': 'Lincoln',          'Flower': 'Goldenrod',                  'Population': '1934408'},
'Nevada' :          {'Capital': 'Carson City',      'Flower': 'Sagebrush',                  'Population': '3080156'},
'New Hampshire' :   {'Capital': 'Concord',          'Flower': 'Purple lilac',               'Population': '1359711'},
'New Jersey' :      {'Capital': 'Trenton',          'Flower': 'Purple violet',              'Population': '8882190'},
'New Mexico' :      {'Capital': 'Santa Fe',         'Flower': 'Yucca',                      'Population': '2096829'},
'New York' :        {'Capital': 'Raleigh',          'Flower': 'Rose',                       'Population': '19453561'},
'North Carolina' :  {'Capital': 'Bismarck',         'Flower': 'Dogwood',                    'Population': '10488084'},
'North Dakota' :    {'Capital': 'Albany',           'Flower': 'Wild prairie rose',          'Population': '762062'},
'Ohio' :            {'Capital': 'Columbus',         'Flower': 'Scarlet carnation',          'Population': '11689100'},
'Oklahoma' :        {'Capital': 'Oklahoma City',    'Flower': 'Mistletoe',                  'Population': '3956971'},
'Oregon' :          {'Capital': 'Salem',            'Flower': 'Oregon grape',               'Population': '4217737'},
'Pennsylvania' :    {'Capital': 'Harrisburg',       'Flower': 'Mountain laurel',            'Population': '12801989'},
'Rhode Island' :    {'Capital': 'Providence',       'Flower': 'Violet',                     'Population': '1059361'},
'South Carolina' :  {'Capital': 'Columbia',         'Flower': 'Carolina yellow jessamine',  'Population': '5148714'},
'South Dakota' :    {'Capital': 'Pierre',           'Flower': 'American pasqueflower',      'Population': '884659'},
'Tennessee' :       {'Capital': 'Nashville',        'Flower': 'Iris',                       'Population': '6829174'},
'Texas' :           {'Capital': 'Austin',           'Flower': 'Bluebonnet',                 'Population': '28995881'},
'Utah' :            {'Capital': 'Salt Lake City',   'Flower': 'Sego lily',                  'Population': '3205958'},
'Vermont' :         {'Capital': 'Montpelier',       'Flower': 'Red clover',                 'Population': '623989'},
'Virginia' :        {'Capital': 'Richmond',         'Flower': 'American dogwood',           'Population': '8535519'},
'Washington' :      {'Capital': 'Olympia',          'Flower': 'Coast rhododendron',         'Population': '7614893'},
'West Virginia' :   {'Capital': 'Charleston',       'Flower': 'Rhododendron',               'Population': '1792147'},
'Wisconsin' :       {'Capital': 'Madison',          'Flower': 'Wood violet',                'Population': '5822434'},
'Wyoming' :         {'Capital': 'Cheyenne',         'Flower': 'Indian paintbrush',          'Population': '578759'},
}